# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='origin_state',
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='size',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='conversion_factor',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
    ]
