# Generated by Django 5.2.17 on 2026-10-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariety',
            unique_together={('product', 'variety_name')},
        ),
        migrations.RemoveField(
            model_name='productvariety',
            name='grade',
        ),
    ]
