# Generated by Django 5.2.17 on 2026-09-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order_no', models.CharField(max_length=50, unique=True)),
                ('warehouse_name', models.CharField(blank=True, default='Central Cold Hub', max_length=100)),
                ('truck_number', models.CharField(blank=True, default='', max_length=50)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('payment_terms', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI Payment'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('CREDIT', 'Credit (7-14 Days)'), ('CHEQUE', 'Cheque')], default='CREDIT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loading_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid In Full'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_reference', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_boxes', models.IntegerField(default=0)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariety')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
