# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='time_slot',
        ),
    ]
