# Generated by Django 5.2.17 on 2026-10-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_margin',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='warehouse_name',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='cost_rate',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='gross_margin',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='lot_reference',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quality_grade',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tare_weight',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tax_rate',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
    ]
