# Generated by Django 5.2.17 on 2026-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('state', models.CharField(default='Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_type', models.CharField(choices=[('RETAILER', 'Retailer'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('HOTEL', 'Hotel / Restaurant'), ('SUPERMARKET', 'Supermarket'), ('EXPORTER', 'Exporter'), ('OTHER', 'Other')], default='WHOLESALER', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_terms', models.CharField(default='7 Days', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
