# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_city_remove_customer_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_terms',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
