# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
    ]
