# Generated by Django 5.2.17 on 2026-10-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_bank_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
