# Generated by Django 6.1 on 2026-10-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplier_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
    ]
