# Generated by Django 6.1 on 2026-10-02 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_category_description_and_more'),
        ('purchases', '0002_remove_purchaseorder_arrival_date_and_more'),
        ('suppliers', '0003_remove_supplier_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=60, unique=True)),
                ('truck_number', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse_name', models.CharField(default='Central Cold Hub', max_length=100)),
                ('purchase_date', models.DateField()),
                ('received_boxes', models.IntegerField(default=0)),
                ('available_boxes', models.IntegerField(default=0)),
                ('received_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('landed_cost_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('landed_cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPLETED', 'Depleted'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='products.product')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='purchases.purchaseorderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='suppliers.supplier')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='products.productvariety')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse_name', models.CharField(default='Central Cold Hub', max_length=100)),
                ('transaction_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_ISSUE', 'Sales Issue'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('WASTAGE', 'Wastage / Damage'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('WAREHOUSE_TRANSFER', 'Warehouse Transfer')], max_length=30)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=60)),
                ('quantity_boxes', models.IntegerField(default=0)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventorylot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.productvariety')),
            ],
            options={
                'ordering': ['-date_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(default='Central Cold Hub', max_length=100)),
                ('total_boxes', models.IntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_cost_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.productvariety')),
            ],
            options={
                'unique_together': {('product', 'variety', 'warehouse_name')},
            },
        ),
    ]
