# Generated by Django 5.2.17 on 2026-09-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_no', models.CharField(max_length=50, unique=True)),
                ('warehouse_name', models.CharField(blank=True, default='Central Cold Hub', max_length=100)),
                ('truck_number', models.CharField(blank=True, default='', max_length=50)),
                ('purchase_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('TRUCK_ARRIVED', 'Truck Arrived'), ('RECEIVING', 'Receiving Goods'), ('QUALITY_CHECK', 'Quality Check'), ('RECEIVED', 'Goods Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loading_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unloading_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_boxes', models.IntegerField(default=0)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('landed_cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('damage_boxes', models.IntegerField(default=0)),
                ('accepted_boxes', models.IntegerField(default=0)),
                ('damage_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accepted_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariety')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierTruckPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('fruit_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('no_of_boxes', models.IntegerField(default=0)),
                ('pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unloading_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('landed_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('landed_cost_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_payments', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_payments', to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
