# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='time_slot',
        ),
    ]
