# Generated by Django 5.2.17 on 2026-10-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaseorder_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='commission_charge',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='loading_charge',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='transport_charge',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unloading_charge',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='accepted_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='damage_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='landed_cost_per_kg',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='quality_grade',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tare_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tax_rate',
        ),
    ]
